=== msd1kpei/OR01-ARMSMember/OR01-ARMSMember/xsd/ARMSMember-request.xsd
<?xml version='1.0' encoding='UTF-8'?>
<xs:schema xmlns="http://www.kpei.co.id/schema/Member.001" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://www.kpei.co.id/DataFeedNettedTradeRequest" xmlns:ns2="http://www.kpei.co.id/ARMSOfflineCollateralRequest" xmlns:ns3="http://www.kpei.co.id/RMOLNetPositionRequest" targetNamespace="http://www.kpei.co.id/schema/Member.001" elementFormDefault="qualified" attributeFormDefault="unqualified">
   <xs:element name="MemberDelete">
      <xs:annotation>
         <xs:documentation>ARMS Member delete inbound</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element name="header" type="middlewareHeader"/>
            <xs:element name="body">
               <xs:complexType>
                  <xs:sequence>
                     <xs:element name="idMember" type="xs:string" maxOccurs="unbounded"/>
                  </xs:sequence>
               </xs:complexType>
            </xs:element>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:element name="MemberUpdate">
      <xs:annotation>
         <xs:documentation>ARMS Member EOD, updates and inserts inbound</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element name="header" type="middlewareHeader"/>
            <xs:element name="type" type="xs:string">
               <xs:annotation>
                  <xs:documentation>EOD/ INTRA</xs:documentation>
               </xs:annotation>
            </xs:element>
            <xs:element name="body">
               <xs:complexType>
                  <xs:sequence>
                     <xs:element name="riskPointDomain">
                        <xs:complexType>
                           <xs:sequence>
                              <xs:element name="record" maxOccurs="unbounded">
                                 <xs:complexType>
                                    <xs:sequence>
                                       <xs:element name="parents" minOccurs="0">
                                          <xs:complexType>
                                             <xs:sequence>
                                                <xs:element name="parent" minOccurs="1">
                                                   <xs:complexType>
                                                      <xs:attribute name="id" type="xs:string">
                                                         <xs:annotation>
                                                            <xs:documentation>ID Parent</xs:documentation>
                                                         </xs:annotation>
                                                      </xs:attribute>
                                                   </xs:complexType>
                                                </xs:element>
                                             </xs:sequence>
                                          </xs:complexType>
                                       </xs:element>
                                       <xs:element name="fields">
                                          <xs:complexType>
                                             <xs:sequence>
                                                <xs:element name="field" minOccurs="3" maxOccurs="4">
                                                   <xs:annotation>
                                                      <xs:documentation>Value of column; DESCRIPTION = Member Long Name, MEMBER TYPE = Member Type - Must be the string representation, OPERATING STATUS = Member Operating Status - Must be the string representation, SUSPENSION TYPE = {If the member’s status field is set to either “Closed” or “Active” then the value of the suspension type is to be set to Nothing (field should be explicitly null).
If the member’s status field is set to either “Restricted” or “Suspended” then the value of the suspension type is NOT to be set (explicitly omit this field from the delta update). }</xs:documentation>
                                                   </xs:annotation>
                                                   <xs:complexType>
                                                      <xs:simpleContent>
                                                         <xs:extension base="xs:string">
                                                            <xs:attribute name="id" type="xs:string">
                                                               <xs:annotation>
                                                                  <xs:documentation>Name of Column; By default, it should be DESCRIPTION, MEMBER TYPE, OPERATING STATUS, SUSPENSION TYPE</xs:documentation>
                                                               </xs:annotation>
                                                            </xs:attribute>
                                                         </xs:extension>
                                                      </xs:simpleContent>
                                                   </xs:complexType>
                                                </xs:element>
                                             </xs:sequence>
                                          </xs:complexType>
                                       </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string">
                                       <xs:annotation>
                                          <xs:documentation>ID member</xs:documentation>
                                       </xs:annotation>
                                    </xs:attribute>
                                 </xs:complexType>
                              </xs:element>
                           </xs:sequence>
                        </xs:complexType>
                     </xs:element>
                  </xs:sequence>
               </xs:complexType>
            </xs:element>
            <xs:element name="ext" type="expandableVariable"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:element name="MemberToARMS">
      <xs:annotation>
         <xs:documentation>e-CLEARS member to ARMS</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element name="header" type="middlewareHeader"/>
            <xs:element name="body">
               <xs:complexType>
                  <xs:sequence>
                     <xs:element ref="e-CLEARSMember" maxOccurs="unbounded"/>
                  </xs:sequence>
               </xs:complexType>
            </xs:element>
            <xs:element name="ext" type="expandableVariable"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:complexType name="expandableVariable">
      <xs:annotation>
         <xs:documentation>Array of variable for extending parameters</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="value" minOccurs="0" maxOccurs="unbounded">
            <xs:annotation>
               <xs:documentation>value of parameter</xs:documentation>
            </xs:annotation>
            <xs:complexType>
               <xs:simpleContent>
                  <xs:extension base="xs:string">
                     <xs:attribute name="id" type="xs:string">
                        <xs:annotation>
                           <xs:documentation>name of parameter</xs:documentation>
                        </xs:annotation>
                     </xs:attribute>
                  </xs:extension>
               </xs:simpleContent>
            </xs:complexType>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="middlewareHeader">
      <xs:annotation>
         <xs:documentation>Standard Middleware Header</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="asAt" type="xs:dateTime">
            <xs:annotation>
               <xs:documentation>timestamp; ex. 2010-01-01T01:01:01 </xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="source" type="xs:string">
            <xs:annotation>
               <xs:documentation>source system; ex. Datafeed</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
      <xs:attribute name="id" type="xs:string">
         <xs:annotation>
            <xs:documentation>id for distinguish between message; can be sequence or filename_yyyymmddh24miss</xs:documentation>
         </xs:annotation>
      </xs:attribute>
   </xs:complexType>
   <xs:element name="e-CLEARSMember">
      <xs:complexType>
         <xs:sequence>
            <xs:element name="CON_PERS_1" type="xs:string"/>
            <xs:element name="CON_PERS_2" type="xs:string"/>
            <xs:element name="CODE_ZIP" type="xs:string"/>
            <xs:element name="CODE_COU" type="xs:integer" nillable="true"/>
            <xs:element name="CODE_MEM_CAT" type="xs:integer" nillable="true"/>
            <xs:element name="CODE_MRKT_RATE" type="xs:integer" nillable="true"/>
            <xs:element name="CODE_MEM_STA" type="xs:integer" nillable="true"/>
            <xs:element name="CITY_DSC" type="xs:string"/>
            <xs:element name="DSC_MEM" type="xs:string"/>
            <xs:element name="DSC_MEM_SHORT" type="xs:string"/>
            <xs:element name="EXT_REF" type="xs:string"/>
            <xs:element name="ID_MEM" type="xs:string"/>
            <xs:element name="ID_MEM_CAPCO" type="xs:string"/>
            <xs:element name="ID_MEM_INTE" type="xs:string"/>
            <xs:element name="LST_UPD_TS" type="xs:string"/>
            <xs:element name="MEM_ADR_1" type="xs:string"/>
            <xs:element name="MEM_ADR_2" type="xs:string"/>
            <xs:element name="TYP_MEM" type="xs:integer" nillable="true"/>
            <xs:element name="MEM_CLE_ID_MEM_CAPCO" type="xs:string"/>
            <xs:element name="TAX_NUM" type="xs:string"/>
            <xs:element name="FAX_NBR" type="xs:string"/>
            <xs:element name="PHONE_NBR" type="xs:string"/>
            <xs:element name="WEB_NM" type="xs:string"/>
            <xs:element name="EMAIL_ADR" type="xs:string"/>
            <xs:element name="CODE_BR" type="xs:string" nillable="true"/>
            <xs:element name="parentID" type="xs:string"/>
            <xs:element name="upliftFactor" type="xs:decimal" nillable="true"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
</xs:schema>

=== msd1kpei/OR01-ARMSMember/OR01-ARMSMember/public_html/enrichUpdateEOD-2-Source.xml
<?xml version='1.0' encoding='UTF-8'?>
<MemberUpdate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.kpei.co.id/middleware file:/C:/WORK/DEVELOPMENT/ARIS-KPEI-PROJECT/OR01-ARMSMember/xsd/ARMSMember-request.xsd" xmlns="http://www.kpei.co.id/middleware">
   <header id="id118">
      <asAt>2010-08-20T10:42:48.228</asAt>
      <source>source119</source>
   </header>
   <type>type120</type>
   <body>
      <riskPointDomain>
         <record id="id121">
            <parents>
               <parent id="KPEI_GRP"/>
            </parents>
            <fields>
               <field id="SERVICESERVER">string122</field>
               <field>string123</field>
               <field>string124</field>
            </fields>
         </record>
         <record id="id126">
            <fields>
               <field>string127</field>
               <field>string128</field>
               <field>string129</field>
               <field>string130</field>
            </fields>
         </record>
         <record id="id131">
            <parents>
               <parent/>
            </parents>
            <fields>
               <field>string132</field>
               <field>string133</field>
               <field>string134</field>
               <field>string135</field>
            </fields>
         </record>
      </riskPointDomain>
   </body>
   <ext>
      <value id="id136">string137</value>
      <value id="id138">string139</value>
      <value id="id140">string141</value>
   </ext>
</MemberUpdate>

=== msd1kpei/OR01-ARMSMember/OR01-ARMSMember/public_html/enrichUpdateEOD-3-Source.xml
<?xml version='1.0' encoding='UTF-8'?>
<MemberUpdate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.kpei.co.id/schema/Member.001 file:/C:/WORK/DEVELOPMENT/ARIS-KPEI-PROJECT/OR01-ARMSMember/xsd/ARMSMember-request.xsd" xmlns="http://www.kpei.co.id/schema/Member.001">
   <header id="id31">
      <asAt>2010-08-23T07:30:54.430</asAt>
      <source>source32</source>
   </header>
   <type>type33</type>
   <body>
      <riskPointDomain>
         <record id="id34">
            <fields>
               <field>string35</field>
               <field>string36</field>
               <field>string37</field>
            </fields>
         </record>
         <record id="id38">
            <parents>
               <parent id="test"/>
            </parents>
            <fields>
               <field>string39</field>
               <field>string40</field>
               <field>string41</field>
            </fields>
         </record>
         <record id="id42">
            <fields>
               <field>string43</field>
               <field>string44</field>
               <field>string45</field>
            </fields>
         </record>
      </riskPointDomain>
   </body>
   <ext>
      <value id="id46">string47</value>
      <value id="id48">string49</value>
      <value id="id50">string51</value>
   </ext>
</MemberUpdate>
